### PR TITLE
Add eslint

### PR DESCRIPTION
**Pull request by joeybaker**
* replaces jshint and jscs with eslint
* cleans up the server lib a bit. It doesn't totally pass the litner, but it's close.

### CODE REVIEW

**Comment by joeybaker** [comment]
@atomify/owners can someone just make sure I'm not crazy here?

**Comment by serapath** [comment]
does eslint fix the code formatting automatically? I thought thats what jscs can do

**Comment by joeybaker** [comment]
@serapath no, it does not. JSCS recently added that ability, but it only works for style errors – nice, but not as important as catching structural errors that eslint catches. 

That said, I'm eagerly waiting for: https://github.com/eslint/eslint/issues/1787

**Comment by serapath** [comment]
ah ok, so that will come to eslint too :-) then i like it :-)

**Comment by joeybaker** [comment]
I've pretty thoroughly tested this. It works.

**Pull request merged**
